apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

namespace: default

labels:
- includeSelectors: true
  pairs:
    prunable: "true"

images:
- name: nginx
  newName: nginx
  newTag: latest

configMapGenerator:
- name: nginx-conf
  files:
  - conf/nginx.conf
  options:
    labels:
      realname-diff/realname: nginx-conf
    # hash suffix is enabled by default

secretGenerator:
- name: htpasswd
  files:
  - conf/.htpasswd
  options:
    labels:
      realname-diff/realname: htpasswd
    # hash suffix is enabled by default
