version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/kubectl-realname_diff/main.go
    binary: kubectl-realname_diff
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/hhiroshell/kubectl-realname-diff/pkg/version.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto
