apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: realname-diff
spec:
  version: {{ .TagName }}
  homepage: https://github.com/hhiroshell/kubectl-realname-diff
  platforms:
  - bin: kubectl-realname_diff
    {{addURIAndSha "https://github.com/hhiroshell/kubectl-realname-diff/releases/download/{{ .TagName }}/kubectl-realname-diff-linux-amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - bin: kubectl-realname_diff
    {{addURIAndSha "https://github.com/hhiroshell/kubectl-realname-diff/releases/download/{{ .TagName }}/kubectl-realname-diff-linux-arm64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: arm64
  - bin: kubectl-realname_diff
    {{addURIAndSha "https://github.com/hhiroshell/kubectl-realname-diff/releases/download/{{ .TagName }}/kubectl-realname-diff-darwin-amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - bin: kubectl-realname_diff
    {{addURIAndSha "https://github.com/hhiroshell/kubectl-realname-diff/releases/download/{{ .TagName }}/kubectl-realname-diff-darwin-arm64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  shortDescription: Diffs live and local resources ignoring Kustomize hash-suffixes
  description: |
    Kubectl realname-diff works the same as kubectl diff, but if you set "real
    name" as a label, local and live resources with the same label will be
    compared.
    This is especially beneficial if you use the Kustomize and enable hash
    suffixing ConfigMap/Secret names. In case of `kubectl diff`, local and live
    resources with hash suffixed name are considered as irrelevant. So you will not
    be able to get any results comparing them.
    With realname-diff, you can compare the resources with hash suffixed name by
    specifying the comparison target with "real name" labels.
